import localFont from "next/font/local";
import "./globals.css";
import Navbar from './components/navbar/Navbar';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden ">
      

        
        <Navbar />
          
        {children}
      </body>
    </html>
  );
}
